"""
Master Mobile Plan (2026) > Update > "Make a change" (row 10) + "Check for
new build" (row 13) - a genuinely device-less pair of test cases.

Both rows were previously marked Not automatable/N/A, on the (reasonable at
the time) assumption they needed a real on-device Maestro/Appium action.
Confirmed live 2026-09-01 by reading commcare-hq source directly that
neither actually does:

- Row 10 ("make a change... do NOT create a new build") is just
  HQClient.edit_module_attr() saving the app's draft content without
  building - see that method's own docstring for the exact
  corehq/apps/app_manager/views/modules.py:edit_module_attr() citation.
- Row 13 ("the previous step should have automatically created a new
  build... comment 'Auto-generated by a phone update'") is CommCareHQ's own
  autogenerate_build() (corehq/apps/app_manager/tasks.py), which fires for
  ANY client - not specifically a phone - that fetches the app's live ODK
  profile while its draft version is ahead of the latest saved build's
  version. See HQClient.check_for_phone_triggered_build()'s own docstring
  for the full citation and the live build (version 75, is_released=False)
  this exact mechanism produced during research.

So this script IS the whole test: no BrowserStack build, no device, no
Maestro flow file - just two authenticated HQ calls plus real verification
that HQ's response matches what the sheet describes. Wired into CI as its
own lightweight job (no BrowserStack device/minute cost) rather than folded
into run_suite.py's device-oriented flow runner.

Usage: python scripts/run_update_content_change_check.py
"""
import os
import pathlib
import sys
import time

sys.path.insert(0, os.path.dirname(__file__))
import hq_client as hq_client_module
import report_generator
from app_registry import APP_REGISTRY

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent

# The "Surveys" module - confirmed live 2026-09-01 to have an empty `comment`
# field before this script ever touched it, and to carry no on-device-visible
# text that any other flow could depend on (comment is never rendered in the
# app's own UI - see edit_module_attr()'s own docstring).
MODULE_UNIQUE_ID = "9a71746c3d353aa83395742dea0f6aafaebe6e0a"


def run(hq, app_id, username, poll_seconds=3, timeout_seconds=60):
    before = hq.list_releases(app_id, only_show_released=False, limit=1)
    before_version = before[0]["version"] if before else None

    change_value = f"QA automated content-change trigger {int(time.time())}"
    hq.edit_module_attr(app_id, MODULE_UNIQUE_ID, "comment", change_value)

    hq.check_for_phone_triggered_build(app_id, username)

    # autogenerate_build() (corehq/apps/app_manager/tasks.py) queues its
    # actual build-creation via Celery's `.delay(...)` - NOT synchronous with
    # the profile.ccpr response, confirmed live 2026-09-01 (an immediate
    # re-list still showed the OLD newest build; the new one appeared within
    # ~3s). Poll the same way download_ccz() already does for its own async
    # HQ job, rather than assume either instant completion or a fixed sleep.
    deadline = time.monotonic() + timeout_seconds
    newest = None
    while True:
        after = hq.list_releases(app_id, only_show_released=False, limit=1)
        if after and after[0]["version"] != before_version:
            newest = after[0]
            break
        if time.monotonic() > deadline:
            raise AssertionError(
                f"No new build appeared within {timeout_seconds}s - newest build is "
                f"still version {before_version}, same as before the content change + "
                f"profile check (autogenerate_build_task may be stuck/queued, or the "
                f"content change didn't register)."
            )
        time.sleep(poll_seconds)
    comment = newest.get("build_comment") or ""
    if not comment.startswith("Auto-generated by a phone update"):
        raise AssertionError(
            f"Newest build (version {newest['version']}) has comment {comment!r}, "
            f"expected it to start with 'Auto-generated by a phone update' - "
            f"either something else built a version in the meantime, or HQ's "
            f"autogenerate_build() text changed."
        )
    if newest.get("is_released"):
        raise AssertionError(
            f"Newest build (version {newest['version']}) came back already "
            f"released - the sheet's own step 2 says 'Do NOT star this build', "
            f"and a freshly auto-generated build should start unreleased."
        )
    return newest


def main():
    from dotenv import load_dotenv
    load_dotenv(REPO_ROOT / ".env")

    domain, app_id = APP_REGISTRY["UPDATE_TEST_ALTERNATE"]
    hq = hq_client_module.HQClient(domain=domain).login(
        username=os.environ.get("HQ_WEB_USER_EMAIL"), password=os.environ.get("HQ_WEB_USER_PASSWORD"),
    )
    username = os.environ.get("CC_TEST_USERNAME", "qa_automation")

    start = time.monotonic()
    try:
        newest = run(hq, app_id, username)
        result = report_generator.TestResult(
            name="update/check_for_new_build",
            workflow="update",
            status="passed",
            duration_ms=int((time.monotonic() - start) * 1000),
            device="N/A (HQ API only, no device)",
        )
        print(f"PASS: new build version {newest['version']} auto-generated, "
              f"comment={newest['build_comment']!r}, is_released={newest['is_released']}")
    except Exception as exc:  # noqa: BLE001 - report the real failure, don't mask it
        result = report_generator.TestResult(
            name="update/check_for_new_build",
            workflow="update",
            status="failed",
            duration_ms=int((time.monotonic() - start) * 1000),
            device="N/A (HQ API only, no device)",
            error=str(exc),
            failed_step=f"check_for_new_build - {exc}",
        )
        print(f"FAIL: {exc}")

    (REPO_ROOT / "reports").mkdir(exist_ok=True)
    apk_version_path = REPO_ROOT / "reports" / "apk_version.txt"
    if not apk_version_path.exists():
        apk_version_path.write_text("N/A (HQ API only, no device)", encoding="utf-8")

    build_id = f"update-content-check-{int(time.time())}"
    report_path = report_generator.generate_report(build_id, [result], enrich=False)
    print(f"Report written to {report_path}")

    if result.status == "failed":
        sys.exit(1)


if __name__ == "__main__":
    main()
